#pragma once

// This file is generated by scripts/make_single_header.py.
// Do not edit it manually.

#include <chrono>
#include <string_view>

namespace profkit {

enum class TimeUnit {
  kMilliseconds,
  kSeconds,
};

using ScopeId = std::uint32_t;

ScopeId RegisterScope(std::string_view name);

class ScopeTimer {
 public:
  explicit ScopeTimer(ScopeId scope_id);
  ~ScopeTimer();

  void Stop();

  ScopeTimer(const ScopeTimer&) = delete;
  ScopeTimer& operator=(const ScopeTimer&) = delete;

  ScopeTimer(ScopeTimer&&) = delete;
  ScopeTimer& operator=(ScopeTimer&&) = delete;

 private:
  ScopeId scope_id_;
  std::uint64_t start_ns_;
  bool stopped_ = false;
};

class Session {
 public:
  explicit Session(std::string_view name);
  ~Session();

  Session(const Session&) = delete;
  Session& operator=(const Session&) = delete;

  Session(Session&&) = delete;
  Session& operator=(Session&&) = delete;

 private:
  ScopeTimer timer_;
};

void SetTimeUnit(TimeUnit unit);
TimeUnit GetTimeUnit();

void PrintReport();
void Reset();
void DumpAndReset();

}  // namespace profkit

#define PROFKIT_CONCAT_IMPL(a, b) a##b
#define PROFKIT_CONCAT(a, b) PROFKIT_CONCAT_IMPL(a, b)

#define PROF_DUMP() ::profkit::PrintReport()
#define PROF_RESET() ::profkit::Reset()
#define PROF_DUMP_AND_RESET() ::profkit::DumpAndReset()

#define PROF_USE_SECONDS() ::profkit::SetTimeUnit(::profkit::TimeUnit::kSeconds)
#define PROF_USE_MILLISECONDS() ::profkit::SetTimeUnit(::profkit::TimeUnit::kMilliseconds)

#if defined(__GNUC__) || defined(__clang__)
#define PROFKIT_FUNCTION_NAME __PRETTY_FUNCTION__
#elif defined(_MSC_VER)
#define PROFKIT_FUNCTION_NAME __FUNCSIG__
#else
#define PROFKIT_FUNCTION_NAME __func__
#endif

#if defined(PROFKIT_ENABLE) && PROFKIT_ENABLE

#define PROF_SCOPE(name)                                                        \
  static const ::profkit::ScopeId PROFKIT_CONCAT(profkit_scope_id_, __LINE__) = \
      ::profkit::RegisterScope(name);                                           \
  ::profkit::ScopeTimer PROFKIT_CONCAT(profkit_timer_,                          \
                                       __LINE__)(PROFKIT_CONCAT(profkit_scope_id_, __LINE__))

#define PROF_FUNCTION() PROF_SCOPE(PROFKIT_FUNCTION_NAME)

#define PROF_SESSION(name) ::profkit::Session PROFKIT_CONCAT(profkit_session_, __LINE__)(name)

#else

#define PROF_SCOPE(name) static_cast<void>(0)
#define PROF_FUNCTION() static_cast<void>(0)
#define PROF_SESSION(name) static_cast<void>(0)

#endif

#ifdef PROFKIT_IMPLEMENTATION

#include <algorithm>
#include <chrono>
#include <iomanip>
#include <iostream>
#include <limits>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

namespace profkit {
namespace {
struct ScopeInfo {
  std::string name;
};

struct ScopeStat {
  std::uint64_t calls = 0;

  std::uint64_t total_ns = 0;
  std::uint64_t min_ns = std::numeric_limits<std::uint64_t>::max();
  std::uint64_t max_ns = 0;

  std::uint64_t first_start_ns = std::numeric_limits<std::uint64_t>::max();
  std::uint64_t last_end_ns = 0;
};

void AddSample(ScopeStat& stat, std::uint64_t start_ns, std::uint64_t end_ns) {
  const std::uint64_t elapsed_ns = end_ns - start_ns;

  ++stat.calls;

  stat.total_ns += elapsed_ns;
  stat.min_ns = std::min(stat.min_ns, elapsed_ns);
  stat.max_ns = std::max(stat.max_ns, elapsed_ns);

  stat.first_start_ns = std::min(stat.first_start_ns, start_ns);
  stat.last_end_ns = std::max(stat.last_end_ns, end_ns);
}

void MergeStat(ScopeStat& dst, const ScopeStat& src) {
  if (src.calls == 0) {
    return;
  }

  dst.calls += src.calls;
  dst.total_ns += src.total_ns;

  dst.min_ns = std::min(dst.min_ns, src.min_ns);
  dst.max_ns = std::max(dst.max_ns, src.max_ns);

  dst.first_start_ns = std::min(dst.first_start_ns, src.first_start_ns);
  dst.last_end_ns = std::max(dst.last_end_ns, src.last_end_ns);
}

class ProfilerStorage {
 public:
  ScopeId RegisterScope(std::string_view name) {
    std::lock_guard lock(mutex_);

    const std::string key{name};
    const auto it = ids_by_name_.find(key);
    if (it != ids_by_name_.end()) {
      return it->second;
    }

    const auto id = static_cast<ScopeId>(scopes_.size());

    scopes_.push_back(ScopeInfo{.name = key});
    ids_by_name_.emplace(scopes_.back().name, id);

    return id;
  }

  std::uint32_t RegisterThread() {
    std::lock_guard lock(mutex_);
    return next_thread_id_++;
  }

  void AddFinishedThreadStats(std::vector<ScopeStat> stats) {
    std::lock_guard lock(mutex_);
    finished_thread_stats_.push_back(std::move(stats));
  }

  void PrintReportWithCurrentThreadStats(const std::vector<ScopeStat>& current_thread_stats) {
    std::lock_guard lock(mutex_);

    std::vector<std::vector<ScopeStat>> all_thread_stats = finished_thread_stats_;
    all_thread_stats.push_back(current_thread_stats);

    std::vector<ScopeStat> total_stats(scopes_.size());
    std::vector<std::uint64_t> max_thread_total_ns(scopes_.size(), 0);

    for (const auto& thread_stats : all_thread_stats) {
      for (ScopeId id = 0; id < thread_stats.size() && id < scopes_.size(); ++id) {
        const auto& stat = thread_stats[id];

        if (stat.calls == 0) {
          continue;
        }

        MergeStat(total_stats[id], stat);
        max_thread_total_ns[id] = std::max(max_thread_total_ns[id], stat.total_ns);
      }
    }

    PrintTable(total_stats, max_thread_total_ns);
  }

  void Reset() {
    std::lock_guard lock(mutex_);
    finished_thread_stats_.clear();
  }

  void SetTimeUnit(TimeUnit unit) {
    std::lock_guard lock(mutex_);
    time_unit_ = unit;
  }

  TimeUnit GetTimeUnit() const {
    std::lock_guard lock(mutex_);
    return time_unit_;
  }

 private:
  void PrintTable(const std::vector<ScopeStat>& total_stats,
                  const std::vector<std::uint64_t>& max_thread_total_ns) const {
    std::cout << "\nProfiler report\n";
    std::cout << std::string(145, '=') << "\n\n";

    const std::string unit = TimeUnitSuffix();

    // clang-format off
    std::cout << std::left << std::setw(45) << "scope"
              << std::right << std::setw(10) << "calls"
              << std::setw(14) << ("wall " + unit)
              << std::setw(16) << ("cpu total " + unit)
              << std::setw(14) << ("avg " + unit)
              << std::setw(14) << ("min " + unit)
              << std::setw(14) << ("max " + unit)
              << std::setw(18) << ("max thread " + unit)
              << '\n';
    // clang-format on

    std::cout << std::string(145, '-') << '\n';

    for (ScopeId id = 0; id < scopes_.size(); ++id) {
      const auto& stat = total_stats[id];

      if (stat.calls == 0) {
        continue;
      }

      const double wall_time = ConvertNs(stat.last_end_ns - stat.first_start_ns);
      const double cpu_total_time = ConvertNs(stat.total_ns);
      const double avg_time = ConvertNs(stat.total_ns / stat.calls);
      const double min_time = ConvertNs(stat.min_ns);
      const double max_time = ConvertNs(stat.max_ns);
      const double max_thread_time = ConvertNs(max_thread_total_ns[id]);

      // clang-format off
      std::cout << std::left << std::setw(45) << scopes_[id].name
                << std::right << std::setw(10) << stat.calls
                << std::setw(14) << std::fixed << std::setprecision(3) << wall_time
                << std::setw(16) << cpu_total_time
                << std::setw(14) << avg_time
                << std::setw(14) << min_time
                << std::setw(14) << max_time
                << std::setw(18) << max_thread_time
                << '\n';
      // clang-format on
    }
  }

  double ConvertNs(std::uint64_t ns) const {
    switch (time_unit_) {
      case TimeUnit::kSeconds:
        return static_cast<double>(ns) / 1'000'000'000.0;

      case TimeUnit::kMilliseconds:
        return static_cast<double>(ns) / 1'000'000.0;
    }

    return static_cast<double>(ns) / 1'000'000.0;
  }

  const char* TimeUnitSuffix() const {
    switch (time_unit_) {
      case TimeUnit::kSeconds:
        return "s";

      case TimeUnit::kMilliseconds:
        return "ms";
    }

    return "ms";
  }

  mutable std::mutex mutex_;

  std::vector<ScopeInfo> scopes_;
  std::unordered_map<std::string, ScopeId> ids_by_name_;

  std::vector<std::vector<ScopeStat>> finished_thread_stats_;

  std::uint32_t next_thread_id_ = 0;

  TimeUnit time_unit_ = TimeUnit::kMilliseconds;
};

ProfilerStorage& Storage() {
  static auto* storage = new ProfilerStorage();
  return *storage;
}

std::uint64_t NowNs() {
  static const auto start = std::chrono::steady_clock::now();
  return static_cast<std::uint64_t>(
      std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now() - start)
          .count());
}

std::uint64_t ToNs(std::chrono::steady_clock::duration duration) {
  return static_cast<std::uint64_t>(
      std::chrono::duration_cast<std::chrono::nanoseconds>(duration).count());
}

struct ThreadState {
  ThreadState() : thread_id(Storage().RegisterThread()) {}

  ~ThreadState() {
    Storage().AddFinishedThreadStats(std::move(stats));
  }

  void AddSample(ScopeId id, std::uint64_t start_ns, std::uint64_t end_ns) {
    if (id >= stats.size()) {
      stats.resize(static_cast<std::size_t>(id) + 1);
    }

    ::profkit::AddSample(stats[id], start_ns, end_ns);
  }

  std::uint32_t thread_id = 0;
  std::vector<ScopeStat> stats;
};

ThreadState& CurrentThreadState() {
  thread_local ThreadState state;
  return state;
}

void ResetCurrentThreadStats() {
  CurrentThreadState().stats.clear();
}

}  // namespace

ScopeId RegisterScope(std::string_view name) {
  return Storage().RegisterScope(name);
}

ScopeTimer::ScopeTimer(ScopeId scope_id) : scope_id_(scope_id), start_ns_(NowNs()) {}

ScopeTimer::~ScopeTimer() {
  Stop();
}

void ScopeTimer::Stop() {
  if (stopped_) {
    return;
  }

  CurrentThreadState().AddSample(scope_id_, start_ns_, NowNs());
  stopped_ = true;
}

Session::Session(std::string_view name) : timer_(RegisterScope(name)) {}

Session::~Session() {
  timer_.Stop();
  PrintReport();
}

void PrintReport() {
  Storage().PrintReportWithCurrentThreadStats(CurrentThreadState().stats);
}

void Reset() {
  Storage().Reset();
  ResetCurrentThreadStats();
}

void DumpAndReset() {
  PrintReport();
  Reset();
}

void SetTimeUnit(TimeUnit unit) {
  Storage().SetTimeUnit(unit);
}

TimeUnit GetTimeUnit() {
  return Storage().GetTimeUnit();
}

}  // namespace profkit

#endif  // PROFKIT_IMPLEMENTATION
