#!/usr/bin/env python3

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

HEADER = ROOT / "include" / "profkit" / "profiler.hpp"
SOURCE = ROOT / "src" / "profiler.cpp"
OUTPUT = ROOT / "single_include" / "profkit.hpp"
def strip_pragma_once(text: str) -> str:
    return text.replace("#pragma once\n\n", "").replace("#pragma once\n", "")
def strip_local_include(text: str) -> str:
    return text.replace('#include "profkit/profiler.hpp"\n\n', "")

def main() -> None:
    header = strip_pragma_once(HEADER.read_text())
    source = strip_local_include(SOURCE.read_text())

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    OUTPUT.write_text(
"""#pragma once

// This file is generated by scripts/make_single_header.py.
// Do not edit it manually.

"""
        + header
        + """

#ifdef PROFKIT_IMPLEMENTATION

"""
        + source
        + """

#endif  // PROFKIT_IMPLEMENTATION
"""
    )

if __name__ == "__main__":
    main()